targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/swaggers'
          output_folder: 'lib/swaggers'
          #override_equals_and_hashcode: false
          build_only_models: true
          separate_models: true
