///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Drawable {
  Drawable._();

  static const String bgLoginTop = 'assets/images/bg_login_top.png';
  static const String iconContact = 'assets/images/icon_contact.png';
  static const String iconEyeclose = 'assets/images/icon_eyeclose.png';
  static const String iconEyeopen = 'assets/images/icon_eyeopen.png';
  static const String iconEyeopenBlack = 'assets/images/icon_eyeopen_black.png';
  static const String iconHomeOff = 'assets/images/icon_home_off.png';
  static const String iconHomeOn = 'assets/images/icon_home_on.png';
  static const String iconLogo = 'assets/images/icon_logo.png';
  static const String iconMineOff = 'assets/images/icon_mine_off.png';
  static const String iconMineOn = 'assets/images/icon_mine_on.png';
  static const String iconRetainLogin1 = 'assets/images/icon_retain_login1.png';
  static const String iconRetainLogin2 = 'assets/images/icon_retain_login2.png';
  static const String iconRetainLogin3 = 'assets/images/icon_retain_login3.png';
  static const String iconSelectOff = 'assets/images/icon_select_off.png';
  static const String iconSelectOn = 'assets/images/icon_select_on.png';
  static const String iconStatusCard = 'assets/images/icon_status_card.png';
  static const String iconStatusLoad1 = 'assets/images/icon_status_load1.png';
  static const String iconStatusLoad2 = 'assets/images/icon_status_load2.png';
  static const String iconStatusLoad3 = 'assets/images/icon_status_load3.png';
  static const String iconStatusOn1 = 'assets/images/icon_status_on1.png';
  static const String iconStatusOn2 = 'assets/images/icon_status_on2.png';
  static const String iconStatusOn3 = 'assets/images/icon_status_on3.png';
  static const String iconStatusRight1 = 'assets/images/icon_status_right1.png';
  static const String iconStatusRight2 = 'assets/images/icon_status_right2.png';
  static const String iconStatusWarn = 'assets/images/icon_status_warn.png';
  static const String iconStatusWifi = 'assets/images/icon_status_wifi.png';
  static const String iconStatusWrong1 = 'assets/images/icon_status_wrong1.png';
  static const String iconStatusWrong2 = 'assets/images/icon_status_wrong2.png';
  static const String iconStatusWrong3 = 'assets/images/icon_status_wrong3.png';
  static const String iconXtcustomer = 'assets/images/icon_xtcustomer.png';
  static const String iconXtleft = 'assets/images/icon_xtleft.png';
  static const String imageGuard = 'assets/images/image_guard.png';
  static const String imageScreenshot1 = 'assets/images/image_screenshot1.png';
  static const String imageScreenshot2 = 'assets/images/image_screenshot2.png';

}
