///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Drawable {
  Drawable._();

  static const String bgLoginTop = 'assets/images/bg_login_top.png';
  static const String iconAboutCopy = 'assets/images/icon_about_copy.png';
  static const String iconAboutForward = 'assets/images/icon_about_forward.png';
  static const String iconAboutPhone = 'assets/images/icon_about_phone.png';
  static const String iconCaptchaBrokea = 'assets/images/icon_captcha_brokea.png';
  static const String iconCaptchaRefresh = 'assets/images/icon_captcha_refresh.png';
  static const String iconContact = 'assets/images/icon_contact.png';
  static const String iconEyeclose = 'assets/images/icon_eyeclose.png';
  static const String iconEyeopen = 'assets/images/icon_eyeopen.png';
  static const String iconEyeopenBlack = 'assets/images/icon_eyeopen_black.png';
  static const String iconHomeOff = 'assets/images/icon_home_off.png';
  static const String iconHomeOn = 'assets/images/icon_home_on.png';
  static const String iconLogo = 'assets/images/icon_logo.png';
  static const String iconMineH1 = 'assets/images/icon_mine_h1.png';
  static const String iconMineH2 = 'assets/images/icon_mine_h2.png';
  static const String iconMineH3 = 'assets/images/icon_mine_h3.png';
  static const String iconMineH4 = 'assets/images/icon_mine_h4.png';
  static const String iconMineLeft = 'assets/images/icon_mine_left.png';
  static const String iconMineNext = 'assets/images/icon_mine_next.png';
  static const String iconMineOff = 'assets/images/icon_mine_off.png';
  static const String iconMineOn = 'assets/images/icon_mine_on.png';
  static const String iconMineRight = 'assets/images/icon_mine_right.png';
  static const String iconMineV1 = 'assets/images/icon_mine_v1.png';
  static const String iconMineV2 = 'assets/images/icon_mine_v2.png';
  static const String iconMineV3 = 'assets/images/icon_mine_v3.png';
  static const String iconQuestion = 'assets/images/icon_question.png';
  static const String iconRetainLogin1 = 'assets/images/icon_retain_login1.png';
  static const String iconRetainLogin2 = 'assets/images/icon_retain_login2.png';
  static const String iconRetainLogin3 = 'assets/images/icon_retain_login3.png';
  static const String iconSelectOff = 'assets/images/icon_select_off.png';
  static const String iconSelectOn = 'assets/images/icon_select_on.png';
  static const String iconStatusCard = 'assets/images/icon_status_card.png';
  static const String iconStatusLoad1 = 'assets/images/icon_status_load1.png';
  static const String iconStatusLoad2 = 'assets/images/icon_status_load2.png';
  static const String iconStatusLoad3 = 'assets/images/icon_status_load3.png';
  static const String iconStatusOn1 = 'assets/images/icon_status_on1.png';
  static const String iconStatusOn2 = 'assets/images/icon_status_on2.png';
  static const String iconStatusOn3 = 'assets/images/icon_status_on3.png';
  static const String iconStatusRight1 = 'assets/images/icon_status_right1.png';
  static const String iconStatusRight2 = 'assets/images/icon_status_right2.png';
  static const String iconStatusWarn = 'assets/images/icon_status_warn.png';
  static const String iconStatusWifi = 'assets/images/icon_status_wifi.png';
  static const String iconStatusWrong1 = 'assets/images/icon_status_wrong1.png';
  static const String iconStatusWrong2 = 'assets/images/icon_status_wrong2.png';
  static const String iconStatusWrong3 = 'assets/images/icon_status_wrong3.png';
  static const String iconXtcustomer = 'assets/images/icon_xtcustomer.png';
  static const String iconXtleft = 'assets/images/icon_xtleft.png';
  static const String imageDpi = 'assets/images/image_dpi.png';
  static const String imageGoodview = 'assets/images/image_goodview.png';
  static const String imageGuard = 'assets/images/image_guard.png';
  static const String imageScreenshot1 = 'assets/images/image_screenshot1.png';
  static const String imageScreenshot2 = 'assets/images/image_screenshot2.png';
  static const String imageUpgrade = 'assets/images/image_upgrade.png';

}
